# Generated by Django 4.1.5 on 2023-01-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id_dashboard', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('periodicity', models.CharField(max_length=100)),
                ('business_unit', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('id_data_domain', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataOwner',
            fields=[
                ('id_data_owner', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id_rule', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('data_dimension', models.CharField(choices=[('timeliness', 'timeliness'), ('completeness', 'completeness'), ('consistency', 'consistency'), ('conformity', 'conformity'), ('accuracy', 'accuracy'), ('integrity', 'integrity')], max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Test', max_length=100)),
                ('data_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.datadomain')),
                ('data_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.dataowner')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardsRules',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('id_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.dashboards')),
                ('id_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.rules')),
            ],
        ),
    ]
