# Generated by Django 4.1.5 on 2023-01-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_rules_data_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
