# Generated by Django 4.1.5 on 2023-01-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_rules_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='suspension_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datadomain',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datadomain',
            name='suspension_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataowner',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dataowner',
            name='suspension_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='data_dimension',
            field=models.CharField(choices=[('Timeliness', 'Timeliness'), ('Completeness', 'Completeness'), ('Consistency', 'Consistency'), ('Uniqueness', 'Uniqueness'), ('Accuracy', 'Accuracy'), ('Integrity', 'Integrity')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='suspension_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
