# Generated by Django 4.1.5 on 2023-01-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_alter_dashboards_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='suspension_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datadomain',
            name='suspension_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataowner',
            name='suspension_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='suspension_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
