# Generated by Django 4.1.5 on 2023-02-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_alter_rules_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='data_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_domain', to='djangoapp.datadomain'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='data_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_owner', to='djangoapp.dataowner'),
        ),
    ]
