# Generated by Django 4.1.5 on 2023-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_alter_rules_data_domain_alter_rules_data_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='data_dimension',
            field=models.CharField(choices=[('TIME', 'Timeliness'), ('COMP', 'Completeness'), ('CONS', 'Consistency'), ('UNIQ', 'Uniqueness'), ('ACCU', 'Accuracy'), ('INTE', 'Integrity')], max_length=100, null=True),
        ),
    ]
