# Generated by Django 4.1.5 on 2023-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_alter_rules_data_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadomain',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dataowner',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
