# Generated by Django 4.1.5 on 2023-02-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_alter_datadomain_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='data_domain',
            new_name='id_data_domain',
        ),
        migrations.RenameField(
            model_name='rules',
            old_name='data_owner',
            new_name='id_data_owner',
        ),
    ]
