# Generated by Django 4.1.5 on 2023-02-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_rename_id_data_domain_rules_data_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardsRules',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='djangoapp.dashboards')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='djangoapp.rules')),
            ],
        ),
    ]
