# Generated by Django 4.1.5 on 2023-02-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_dashboardsrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsrules',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardsrules',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='data_domain',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='data_owner',
        ),
        migrations.DeleteModel(
            name='Dashboards',
        ),
        migrations.DeleteModel(
            name='DashboardsRules',
        ),
        migrations.DeleteModel(
            name='DataDomain',
        ),
        migrations.DeleteModel(
            name='DataOwner',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
