# Generated by Django 4.1.5 on 2023-02-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangoapp', '0014_remove_dashboardsrules_dashboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('periodicity', models.CharField(max_length=100)),
                ('business_unit', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(default='Test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(default='Test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(default='Test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('data_dimension', models.CharField(choices=[('TIME', 'Timeliness'), ('COMP', 'Completeness'), ('CONS', 'Consistency'), ('UNIQ', 'Uniqueness'), ('ACCU', 'Accuracy'), ('INTE', 'Integrity')], max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(default='Test', max_length=100)),
                ('data_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_domain', to='djangoapp.datadomain')),
                ('data_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_owner', to='djangoapp.dataowner')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardsRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='djangoapp.dashboards')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='djangoapp.rules')),
            ],
        ),
    ]
